name: brackets
version: '1.11'
summary: Brackets is a modern code editor for HTML, CSS and JavaScript.
description: |
 Brackets is an open-source editor for web design and development
 built on top of web technologies such as HTML, CSS and JavaScript.
 The project was created and is maintained by Adobe, and is released
 under an MIT License.

grade: stable
confinement: classic

parts:
  brackets:
    plugin: dump
    source: https://github.com/adobe/brackets/releases/download/release-1.11/Brackets.Release.1.11.64-bit.deb
    source-type: deb
    # Correct path to icon.
    # Delete usr/bin/brackets, it is a broken symlink pointing outside the snap.
    prepare: |
      sed -i 's|Icon=brackets|Icon=/usr/share/icons/hicolor/scalable/apps/brackets\.svg|g' opt/brackets/brackets.desktop
      rm -f usr/bin/brackets
      chmod -s opt/brackets/chrome-sandbox
    after:
      - desktop-gtk2
    stage-packages:
      - gconf2
      - libasound2
      - libnotify4
      - libnspr4
      - libnss3
      - libpulse0
      - libxss1
      - libxtst6
  electron-launch:
    plugin: dump
    source: .
    organize:
      electron-launch: bin/electron-launch

apps:
  brackets:
    command: bin/electron-launch classic ${SNAP}/opt/brackets/brackets
    desktop: opt/brackets/brackets.desktop
